/**
 * Service packages (PRD §7.11, reframed for Avenix Studio's broader MERN
 * positioning). Indicative pricing per PRD — displayed as "from".
 */
export const services = [
  {
    id: 'launch',
    name: 'Launch',
    tagline: 'High-converting single-page presence',
    priceFrom: '$300',
    bestFor: 'Campaigns, single offers, MVP landing pages',
    recommended: false,
    features: [
      'One conversion-focused page',
      'Copy guidance & structure',
      'Lead form + WhatsApp click-to-chat',
      'On-page technical SEO',
      'Core Web Vitals tuned',
    ],
    cta: 'Start a Launch project',
  },
  {
    id: 'business',
    name: 'Business Website',
    tagline: 'The complete brand & lead engine',
    priceFrom: '$700',
    bestFor: 'Clinics, gyms, salons & growing businesses',
    recommended: true,
    features: [
      '5–7 page Next.js website',
      'On-page + local technical SEO',
      'Gallery, reviews & social proof',
      'WhatsApp booking + Maps',
      'Analytics & conversion tracking',
      'Performance & accessibility pass',
    ],
    cta: 'Build my website',
  },
  {
    id: 'app',
    name: 'Custom Web App',
    tagline: 'Full-stack MERN product engineering',
    priceFrom: 'from $2,000',
    bestFor: 'Startups, e-commerce & bespoke platforms',
    recommended: false,
    features: [
      'Full-stack MERN / Next.js application',
      'Auth, database & REST APIs',
      'Third-party integrations',
      'Scalable, maintainable architecture',
      'CI/CD & production hardening',
    ],
    cta: 'Request a custom quote',
  },
  {
    id: 'website-development',
    name: 'Website Development',
    tagline: 'Production-grade Next.js & MERN builds',
    bestFor: 'Businesses needing a fast, scalable website',
    recommended: false,
    features: [
      'Next.js / MERN engineering',
      'Responsive, accessible front-end',
      'CMS, database & API integrations',
      'Core Web Vitals tuned',
      'Deployed, monitored & maintained',
    ],
    cta: 'Build my website',
  },
  {
    id: 'web-design',
    name: 'Web Design',
    tagline: 'Premium, conversion-focused UI/UX',
    bestFor: 'Brands that need to look world-class',
    recommended: false,
    features: [
      'Brand-aligned visual design',
      'Mobile-first, modern layouts',
      'Reusable design system & tokens',
      'Interactive prototypes',
      'Conversion-led structure',
    ],
    cta: 'Design my site',
  },
  {
    id: 'seo',
    name: 'SEO',
    tagline: 'Technical & on-page search optimization',
    bestFor: 'Sites that need to rank and get found',
    recommended: false,
    features: [
      'Technical SEO audit & fixes',
      'On-page + structured data (schema)',
      'Sitemaps, robots & indexing',
      'Speed & Core Web Vitals',
      'Local SEO setup',
    ],
    cta: 'Improve my SEO',
  },
  {
    id: 'ai-automation',
    name: 'AI Automation',
    tagline: 'Automate repetitive business workflows',
    bestFor: 'Teams losing hours to manual tasks',
    recommended: false,
    features: [
      'Workflow & process automation',
      'AI chatbots & assistants',
      'CRM & third-party integrations',
      'Lead capture & routing',
      'Custom AI scripts & APIs',
    ],
    cta: 'Automate my workflow',
  },
  {
    id: 'ai-workflow',
    name: 'AI Workflow',
    tagline: 'AI-assisted delivery, human-owned quality',
    bestFor: 'Faster builds without cutting corners',
    recommended: false,
    features: [
      'AI-accelerated development',
      'Rapid prototyping & iteration',
      'Content & copy assistance',
      'Quality-controlled output',
      'Faster time to launch',
    ],
    cta: 'Start a project',
  },
];
